export const CREATE_NODE_REQUEST = 'CREATE_NODE_REQUEST';
export const CREATE_NODE_SUCCESS = 'CREATE_NODE_SUCCESS';
export const CREATE_NODE_ERROR = 'CREATE_NODE_ERROR';

export const UPDATE_NODE_SUCCESS = 'UPDATE_NODE_SUCCESS';
export const UPDATE_NODE_REQUEST = 'UPDATE_NODE_REQUEST';
export const UPDATE_NODE_ERROR = 'UPDATE_NODE_ERROR';
export const UPDATE_EXPAND_NODE_REQUEST = 'UPDATE_EXPAND_NODE_REQUEST'
export const UPDATE_MOVE_NODE_REQUEST = 'UPDATE_MOVE_NODE_REQUEST'

export const DELETE_NODE_SUCCESS = 'DELETE_NODE_SUCCESS';
export const DELETE_NODE_REQUEST = 'DELETE_NODE_REQUEST';
export const DELETE_NODE_ERROR = 'DELETE_NODE_ERROR';

export const GET_DETAIL_POST_BY_ID_SUCCESS = 'GET_DETAIL_POST_BY_ID_SUCCESS';
export const GET_DETAIL_POST_BY_ID_REQUEST = 'GET_DETAIL_POST_BY_ID_REQUEST';
export const GET_DETAIL_NODE_BY_ID_ERROR = 'GET_DETAIL_NODE_BY_ID_ERROR';
export const GET_COLLECT_IMAGES_FROM_URL_REQUEST = 'GET_COLLECT_IMAGES_FROM_URL_REQUEST';
export const GET_COLLECT_IMAGES_FROM_URL_SUCCESS = 'GET_COLLECT_IMAGES_FROM_URL_SUCCESS';

export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_ERROR = 'CREATE_POST_ERROR';

export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';
export const UPDATE_POST_REQUEST = 'UPDATE_POST_REQUEST';
export const UPDATE_POST_ERROR = 'UPDATE_POST_ERROR';
export const UPDATE_MOVE_POST_REQUEST = 'UPDATE_MOVE_POST_REQUEST'

export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST';

export const GET_NODES_BY_ID_REQUEST = 'GET_NODES_BY_ID_REQUEST';
export const GET_NODES_BY_ID_SUCCESS = 'GET_NODES_BY_ID_SUCCESS';
export const GET_NODES_BY_ID_ERROR = 'GET_NODES_BY_ID_ERROR';
export const SELECT_NODES_IN_TREE_VIEW = 'SELECT_NODES_IN_TREE_VIEW';
export const SET_TITLE_NODE = 'SET_TITLE_NODE';

export const ADD_COMMENT_POST = 'ADD_COMMENT_POST';
export const ADD_COMMENT_POST_SUCCESS = 'ADD_COMMENT_POST_SUCCESS';

export const GET_POSTS_BY_NODE_ID_REQUEST = 'GET_POSTS_BY_NODE_ID_REQUEST';
export const GET_POSTS_BY_NODE_ID_SUCCESS = 'GET_POSTS_BY_NODE_ID_SUCCESS';

export const SET_LOADING_COMMENT = 'SET_LOADING_COMMENT';

export const GET_COMMENT_BY_MAP_ID_REQUEST = 'GET_COMMENT_BY_MAP_ID_REQUEST';
export const GET_COMMENT_BY_MAP_ID_SUCCESS = 'GET_COMMENT_BY_MAP_ID_SUCCESS';

export const RESET_NODE_POST = 'RESET_NODE_POST';

export const RESET_NODE_DETAIL = 'RESET_NODE_DETAIL';

export const RESET_POST_DETAIL = 'RESET_POST_DETAIL';

export const SET_IS_LOADING_CREATE_POST = 'SET_IS_LOADING_CREATE_POST';
export const SET_IS_NOT_LOADING_CREATE_POST = 'SET_IS_NOT_LOADING_CREATE_POST';

export const SET_IS_LOADING_POST = 'SET_IS_LOADING_POST';
export const SET_IS_NOT_LOADING_POST = 'SET_IS_NOT_LOADING_POST';
