export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_IS_NOT_LOADING = 'SET_IS_NOT_LOADING';

export const SET_CONTENT_ERROR = 'SET_CONTENT_ERROR';

export const SET_WIDTH_LEFT_SPLIT = 'SET_WIDTH_LEFT_SPLIT';

export const SET_IS_EDIT_MAP = 'SET_IS_EDIT_MAP';

export const SET_BREADCRUMBS = 'SET_BREADCRUMBS';

export const SET_SHOW_HELPER = 'SET_SHOW_HELPER';

export const GET_FOLLOWING_MAPS_REQUEST = 'GET_FOLLOWING_MAPS_REQUEST';
export const GET_FOLLOWING_MAPS_SUCCESS = 'GET_FOLLOWING_MAPS_SUCCESS';