export const GET_ALL_MAP_DISCOVER_REQUEST = 'GET_ALL_MAP_DISCOVER_REQUEST';
export const CONCAT_DISCOVER = 'CONCAT_DISCOVER';
export const UPDATE_DISCOVER = "UPDATE_DISCOVER"
export const GET_ALL_MAP_DISCOVER_ERROR = 'GET_ALL_MAP_DISCOVER_ERROR';

export const SET_PARAMS_MAP_DISCOVER = 'SET_PARAMS_MAP_DISCOVER';
export const SET_PARAMS_SEARCH_ALL = 'SET_PARAMS_SEARCH_ALL';

export const SEARCH_ALL_REQUEST = 'SEARCH_ALL_REQUEST'
export const SEARCH_ALL_SUCCESS = 'SEARCH_ALL_SUCCESS'
export const UPDATE_MAP_LINKINGMIND = 'UPDATE_MAP_LINKINGMIND';
export const DELETE_MAP_LINKINGMIND = 'DELETE_MAP_LINKINGMIND';