
export const GET_CATEGORY_REQUEST = 'GET_CATEGORY_REQUEST';
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';
export const GET_CATEGORY_ERROR = 'GET_CATEGORY_ERROR';

export const SET_CATEGORY_SELECTED = 'SET_CATEGORY_SELECTED';
export const SET_CATEGORY_SEARCH_DEFAULT = 'SET_CATEGORY_SEARCH_DEFAULT';