export const HANDLE_GET_INFO_REQUEST = 'HANDLE_GET_INFO_REQUEST';
export const HANDLE_GET_INFO_DETAIL_REQUEST = 'HANDLE_GET_INFO_DETAIL_REQUEST';
export const HANDLE_SAVE_INFO_REQUEST = 'HANDLE_SAVE_INFO_REQUEST';
export const HANDLE_FOLLOW_REQUEST = 'HANDLE_FOLLOW_REQUEST';


export const HANDLE_GET_INFO_SUCCESS = 'HANDLE_GET_INFO_SUCCESS';
export const HANDLE_GET_INFO_DETAIL_SUCCESS = 'HANDLE_GET_INFO_DETAIL_SUCCESS';
export const HANDLE_SAVE_INFO_SUCCESS = 'HANDLE_SAVE_INFO_SUCCESS';
export const HANDLE_FOLLOW_SUCCESS = 'HANDLE_FOLLOW_SUCCESS';
export const HANDLE_ADD_PAYMENT_METHOD = 'HANDLE_ADD_PAYMENT_METHOD'
export const HANDLE_DELETE_PAYMENT_METHOD = 'HANDLE_DELETE_PAYMENT_METHOD'
export const HANDLE_DEACTIVE_ACCOUNT = 'HANDLE_DEACTIVE_ACCOUNT'
export const HANDLE_GET_ALL_PLAN_SUCCESS = 'HANDLE_GET_ALL_PLAN_SUCCESS'
export const HANDLE_GET_ALL_PLAN_REQUEST = 'HANDLE_GET_ALL_PLAN_REQUEST'

export const HANDLE_CANCEL_SUBSCRIPTION_SUCCESS = 'HANDLE_CANCEL_SUBSCRIPTION_SUCCESS'
export const HANDLE_CANCEL_SUBSCRIPTION_ERROR = 'HANDLE_CANCEL_SUBSCRIPTION_ERROR'
export const HANDLE_CANCEL_SUBSCRIPTION_REQUEST = 'HANDLE_CANCEL_SUBSCRIPTION_REQUEST'

export const HANDLE_CREATE_SUBSCRIPTION_SUCCESS = 'HANDLE_CREATE_SUBSCRIPTION_SUCCESS'
export const HANDLE_CREATE_SUBSCRIPTION_ERROR = 'HANDLE_CREATE_SUBSCRIPTION_ERROR'
export const HANDLE_CREATE_SUBSCRIPTION_REQUEST = 'HANDLE_CREATE_SUBSCRIPTION_REQUEST'

export const HANDLE_UPDATE_SUBSCRIPTION_SUCCESS = 'HANDLE_UPDATE_SUBSCRIPTION_SUCCESS'
export const HANDLE_UPDATE_SUBSCRIPTION_ERROR = 'HANDLE_UPDATE_SUBSCRIPTION_ERROR'
export const HANDLE_UPDATE_SUBSCRIPTION_REQUEST = 'HANDLE_UPDATE_SUBSCRIPTION_REQUEST'

export const HANDLE_GET_BILLING_DETAIL_REQUEST = 'HANDLE_GET_BILLING_DETAIL_REQUEST'
export const HANDLE_GET_BILLING_DETAIL_SUCCESS = 'HANDLE_GET_BILLING_DETAIL_SUCCESS'
export const HANDLE_GET_BILLING_DETAIL_ERROR = 'HANDLE_GET_BILLING_DETAIL_ERROR'

export const UPDATE_HELPER_USER_SUCCESS = 'UPDATE_HELPER_USER_SUCCESS'
export const UPDATE_HELPER_USER_REQUEST = 'UPDATE_HELPER_USER_REQUEST'
