export const GET_NODE_BY_TAG_REQUEST = 'GET_NODE_BY_TAG_REQUEST'
export const GET_NODE_BY_TAG_SUCCESS = 'GET_NODE_BY_TAG_SUCCESS'
export const ADD_NODE_TO_OTHER_MAP_REQUEST = 'ADD_NODE_TO_OTHER_MAP_REQUEST'
export const ADD_NODE_TO_OTHER_MAP_SUCCESS = 'ADD_NODE_TO_OTHER_MAP_SUCCESS'
