export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_ERROR_REFRESH = 'LOGIN_ERROR_REFRESH';

export const REGISTER_ERROR_REFRESH = 'REGISTER_ERROR_REFRESH';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR';
export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';

export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';
export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';

export const VERIFY_EMAIL_ERROR = 'VERIFY_EMAIL_ERROR';
export const VERIFY_EMAIL_REQUEST = 'VERIFY_EMAIL_REQUEST';

export const RESENT_EMAIL_REQUEST = 'RESENT_EMAIL_REQUEST';
export const RESENT_EMAIL_ERROR = 'RESENT_EMAIL_ERROR';
export const RESENT_EMAIL_SUCCESS = 'RESENT_EMAIL_SUCCESS';

export const UNSUBCRIBE_EMAIL_ERROR = 'UNSUBCRIBE_EMAIL_ERROR';
export const UNSUBCRIBE_EMAIL_REQUEST = 'UNSUBCRIBE_EMAIL_REQUEST';