export const GET_ALL_MAP_REQUEST = 'GET_ALL_MAP_REQUEST';
export const GET_ALL_MAP_SUCCESS = 'GET_ALL_MAP_SUCCESS';
export const GET_ALL_MAP_ERROR = 'GET_ALL_MAP_ERROR';

export const GET_MY_FEED_REQUEST = 'GET_MY_FEED_REQUEST';
export const GET_MY_FEED_SUCCESS = 'GET_MY_FEED_SUCCESS';
export const GET_MY_FEED_ERROR = 'GET_MY_FEED_ERROR';