
export const CREATE_MAP_REQUEST = 'CREATE_MAP_REQUEST';
export const CREATE_MAP_SUCCESS = 'CREATE_MAP_SUCCESS';
export const CREATE_MAP_ERROR = 'CREATE_MAP_ERROR';

export const UPDATE_MAP_REQUEST = 'UPDATE_MAP_REQUEST';
export const UPDATE_MAP_SUCCESS = 'UPDATE_MAP_SUCCESS';
export const UPDATE_MAP_ERROR = 'UPDATE_MAP_ERROR';
export const UPDATE_VIEW_TYPE_MAP_REQUEST = 'UPDATE_VIEW_TYPE_MAP_REQUEST'

export const GET_ALL_BY_CUSTOMER_REQUEST = 'GET_ALL_BY_CUSTOMER_REQUEST';
export const GET_ALL_BY_CUSTOMER_SUCCESS = 'GET_ALL_BY_CUSTOMER_SUCCESS';
export const GET_ALL_BY_USER_ERROR = 'GET_ALL_BY_USER_ERROR';

export const GET_ALL_BY_CUSTOMER_ID_AND_FOLLOWING_REQUEST = 'GET_ALL_BY_CUSTOMER_ID_AND_FOLLOWING_REQUEST';
export const GET_ALL_BY_CUSTOMER_ID_AND_FOLLOWING_SUCCESS = 'GET_ALL_BY_CUSTOMER_ID_AND_FOLLOWING_SUCCESS';

export const GET_MAP_DETAIL_REQUEST = 'GET_MAP_DETAIL_REQUEST';
export const GET_MAP_DETAIL_SUCCESS = 'GET_MAP_DETAIL_SUCCESS';
export const GET_MAP_DETAIL_ERROR = 'GET_MAP_DETAIL_ERROR';

export const DELETE_MAP_REQUEST = 'DELETE_MAP_REQUEST';
export const DELETE_MAP_SUCCESS = 'DELETE_MAP_SUCCESS';
export const DELETE_MAP_ERROR = 'DELETE_MAP_ERROR';

export const GET_POSTS_BY_MAP_ID_REQUEST = 'GET_POSTS_BY_MAP_ID_REQUEST';
export const GET_POSTS_BY_MAP_ID_SUCCESS = 'GET_POSTS_BY_MAP_ID_SUCCESS';
export const GET_POSTS_BY_MAP_ID_ERROR = 'GET_POSTS_BY_MAP_ID_ERROR';

export const COUNT_VIEWER_TO_RECENT = 'COUNT_VIEWER_TO_RECENT';

export const SAVE_FOLLOW_MAP_REQUEST = 'SAVE_FOLLOW_MAP_REQUEST';
export const SAVE_FOLLOW_MAP_SUCCESS = 'SAVE_FOLLOW_MAP_SUCCESS';
export const SAVE_FOLLOW_MAP_ERROR = 'SAVE_FOLLOW_MAP_ERROR';

export const SEARCH_TAGS_REQUEST = 'SEARCH_TAGS_REQUEST';
export const SEARCH_TAGS_SUCCESS = 'SEARCH_TAGS_SUCCESS';

export const SET_SELECT_NODE = 'SET_SELECT_NODE'

export const GET_MIND_MAP_DATA_REQUEST = 'GET_MIND_MAP_DATA_REQUEST'
export const GET_MIND_MAP_DATA_SUCCESS = 'GET_MIND_MAP_DATA_SUCCESS'
export const UPDATE_MIND_MAP_DATA_VIEW = 'UPDATE_MIND_MAP_DATA_VIEW'

export const GET_MIND_MAP_DATA_FOR_ADD_OTHER_NODE_REQUEST = 'GET_MIND_MAP_DATA_FOR_ADD_OTHER_NODE_REQUEST'
export const GET_MIND_MAP_DATA_FOR_ADD_OTHER_NODE_SUCCESS = 'GET_MIND_MAP_DATA_FOR_ADD_OTHER_NODE_SUCCESS'


export const GET_INFO_INVITE_MAP = 'GET_INFO_INVITE_MAP'
export const GET_INFO_INVITE_MAP_SUCCESS = 'GET_INFO_INVITE_MAP_SUCCESS'
export const ADD_USER_INVITE = 'ADD_USER_INVITE'
export const REMOVE_USER_INVITE = 'REMOVE_USER_INVITE'
export const UPDATE_USER_INVITE_PERMISSION = 'UPDATE_USER_INVITE_PERMISSION'

export const GET_ALL_USER_TO_INVITE = 'GET_ALL_USER_TO_INVITE'
export const UPDATE_INVITE_COLLAB = 'UPDATE_INVITE_COLLAB'
export const CONCAT_USER_INVITE_COLLAB = 'CONCAT_USER_INVITE_COLLAB'

export const UPDATE_INVITE_USER = 'UPDATE_INVITE_USER'
export const UPDATE_PERMISSION = 'UPDATE_PERMISSION'
export const REMOVE_PERMISSION = 'REMOVE_PERMISSION'
export const REQUEST_PERMISSION = 'REQUEST_PERMISSION'
export const GENERATE_AND_REMOVE_LINK_REQUEST = 'GENERATE_AND_REMOVE_LINK_REQUEST';
export const GENERATE_AND_REMOVE_LINK_SUCCESS = 'GENERATE_AND_REMOVE_LINK_SUCCESS';
export const GET_MAP_SHARING_MINDMAP = 'GET_MAP_SHARING_MINDMAP';
export const VALIDATE_LINK_REQUEST = 'VALIDATE_LINK_REQUEST';
export const VALIDATE_LINK_SUCCESS = 'VALIDATE_LINK_SUCCESS';

export const SEARCH_MAP_BY_KEY_REQUEST = 'SEARCH_MAP_BY_KEY_REQUEST'
export const SEARCH_MAP_BY_KEY_SUCCESS = 'SEARCH_MAP_BY_KEY_SUCCESS'
export const SEARCH_MAP_BY_KEY_ERROR = 'SEARCH_MAP_BY_KEY_ERROR'
export const SET_LOADING_SEARCH_MY_MAP = 'SET_LOADING_SEARCH_MY_MAP'
export const SET_LOADING_FOLLOW = 'SET_LOADING_FOLLOW'

export const RESET_MINDMAP = 'RESET_MINDMAP';
export const RESET_MAP_DETAIL = 'RESET_MAP_DETAIL';
export const RESET_LIST_USER_INVITE = 'RESET_LIST_USER_INVITE';

export const SEARCH_KEYMAP_REQUEST = 'SEARCH_KEYMAP_REQUEST';
export const SEARCH_KEYMAP_SUCCESS = 'SEARCH_KEYMAP_SUCCESS';

export const SET_BLUR = 'SET_BLUR';

export const GET_PENDING_MAP_SHARING_REQUEST = 'GET_PENDING_MAP_SHARING_REQUEST'
export const GET_PENDING_MAP_SHARING_SUCCESS = 'GET_PENDING_MAP_SHARING_SUCCESS'
export const GET_FOLLOWING_CUSTOMERS_REQUEST = 'GET_FOLLOWING_CUSTOMERS_REQUEST'
export const GET_FOLLOWING_CUSTOMERS_SUCCESS = 'GET_FOLLOWING_CUSTOMERS_SUCCESS'
export const GET_FOLLOWING_CUSTOMERS_ERROR = 'GET_FOLLOWING_CUSTOMERS_ERROR'